[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
relicpay = "5GPVYpyzdosbzWcdttcCdziJVqUCCARf98J857C3T6Gi"

[programs.devnet]
relicpay = "5GPVYpyzdosbzWcdttcCdziJVqUCCARf98J857C3T6Gi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node scripts/test.js"
